package:
    name: numpy
    version: "1.7.1"

source:
    fn: numpy-1.7.1.tar.gz
    url: https://pypi.python.org/packages/source/n/numpy/numpy-1.7.1.tar.gz

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

